import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
test('private persistent records, parsing, replay safety, edits and export',async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'body-journal-test-'));
 const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,DATA_DIR:dir,PORT:'0',HOST:'127.0.0.1',NODE_ENV:'test'}});
 t.after(()=>child.kill('SIGTERM'));
 const origin=await new Promise((resolve,reject)=>{child.stdout.on('data',b=>{const m=b.toString().match(/http:\/\/127\.0\.0\.1:\d+/);if(m)resolve(m[0]);});child.on('error',reject);child.on('exit',()=>reject(new Error('Server stopped before ready')));});
 let cookie='',csrf='';
 const call=async(url,method='GET',payload,overrides={})=>{const res=await fetch(origin+url,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf,...overrides},body:payload===undefined?undefined:JSON.stringify(payload)});return res;};
 assert.equal((await call('/api/records')).status,401);
 assert.equal((await call('/data/journal.sqlite')).status,404);
 assert.equal((await call('/api/register','POST',{username:'TestOwner',password:'test-password-only-123'},{Origin:'https://evil.example'})).status,403);
 const setup=await call('/api/register','POST',{username:'TestOwner',password:'test-password-only-123'});assert.equal(setup.status,200);cookie=setup.headers.get('set-cookie').split(';')[0];csrf=(await setup.json()).csrf;
 assert.equal((await call('/api/records','POST',{text:'75.2',requestId:'request-111111111111'},{'X-CSRF-Token':'wrong'})).status,403);
 const input={text:'2020-10-08 08:00 饭后体重 75.2，腰围84',requestId:'request-111111111111'};
 assert.equal((await call('/api/records','POST',input)).status,201);
 assert.equal((await call('/api/records','POST',input)).status,200);
 assert.equal((await call('/api/records','POST',{...input,requestId:'request-222222222222'})).status,201);
 let records=(await (await call('/api/records')).json()).records;assert.equal(records.length,2);assert.notEqual(records[0].id,records[1].id);assert.equal(records[0].waist,84);assert.equal(records[0].mealContext,'after_meal');
 assert.equal((await call('/api/records','POST',{text:'2020-10-07 75\n目标74',requestId:'request-333333333333'})).status,400);
 assert.equal((await (await call('/api/records')).json()).records.length,2);
 const old=records[0];assert.equal((await call('/api/records/'+old.id,'PATCH',{measuredAt:old.measuredAt,weight:75.1,waist:83.5,updatedAt:old.updatedAt})).status,200);
 assert.equal((await call('/api/records/'+old.id,'PATCH',{measuredAt:old.measuredAt,weight:75,waist:83,updatedAt:old.updatedAt})).status,409);
 assert.equal((await (await call('/api/records')).json()).records[0].mealContext,'after_meal');
 const db=new DatabaseSync(path.join(dir,'journal.sqlite'));assert.equal(db.prepare('SELECT COUNT(*) AS n FROM revisions').get().n,1);db.close();
 const csv=await (await call('/api/export')).text();assert.ok(csv.includes('83.5'));assert.ok(csv.includes('体重'));assert.ok(csv.includes('饭后'));
 const current=(await (await call('/api/records')).json()).records[0];
 assert.equal((await call('/api/records/'+current.id,'PATCH',{...current,mealContext:null})).status,200);
 assert.equal((await (await call('/api/records')).json()).records[0].mealContext,null);
 const invalid={measuredAt:current.measuredAt,weight:74,mealContext:'fasted',requestId:'request-invalid-meal-1234'};
 assert.equal((await call('/api/records','POST',invalid)).status,400);
 assert.equal((await call('/api/records','POST',{...invalid,mealContext:'after_meal'})).status,201);
 assert.equal((await (await call('/api/records')).json()).records.at(-1).mealContext,'after_meal');
 await call('/api/logout','POST',{});assert.equal((await call('/api/records')).status,401);
 const login=await call('/api/login','POST',{username:'TestOwner',password:'test-password-only-123'});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await (await call('/api/records')).json()).records.length,3);
});
